### ISSUE TITLE
Authentication Page Continued

### ISSUE THREAD

**Issue by ClaytonNolen** [ClaytonNolen/GymProgram#11]

**Comment by ClaytonNolen** [comment]
Starting, working on the Auth.svelte file that will be the authentication (login) page.

**Comment by ClaytonNolen** [comment]
Popup window for login with google works!!

**Comment by ClaytonNolen** [comment]
<img width="1714" alt="Screenshot 2024-03-02 at 3 11 27 PM" src="https://github.com/ClaytonNolen/GymProgram/assets/91333063/b36be5ef-22eb-4bc3-8950-e9673b18c47a">

**Comment by ClaytonNolen** [comment]
Have been working on Navigation Bar.

**Comment by ClaytonNolen** [comment]
Importing auth information into navbar display.

**Comment by ClaytonNolen** [comment]
Starting back up on Auth side of project. Wanting the program to listen to auth changes.

**Comment by ClaytonNolen** [comment]
<img width="1703" alt="Screenshot 2024-03-03 at 12 56 20 PM" src="https://github.com/ClaytonNolen/GymProgram/assets/91333063/83a3d23a-1cdb-46b2-b6a6-fe1848a5c8c5">

Users can sign in using Google, the web application will connect via Firebase, and the users picture/nam will update!!!

**Comment by ClaytonNolen** [comment]
Binding info to pages

**Comment by ClaytonNolen** [comment]
Stopping at 23:11 on this video to help binding.

https://www.youtube.com/watch?v=3Q4fK1NdNMQ&t=1241s

**Comment by jedace** [comment]
Picking up on binding inputs and info

**Comment by jedace** [comment]
Stopped updating with firebase and now preview returns 500 error, pausing binding to try and fix errors

**Comment by jedace** [comment]
Continuing to bind inputs on page to our database

**Comment by jedace** [comment]
Coding so that event is saved on page when created, can be used as storing machines or gyms

**Comment by jedace** [comment]
Working on issue where events created dont save to page or database

**Comment by jedace** [comment]
Resuming troubleshooting

**Comment by jedace** [comment]
Working on feature that allows people to join events, will be used as supporting code for adding gyms or equipment to your gym and workout

**Comment by ClaytonNolen** [comment]
Finishing up binding from the remaining pages.

**Comment by ClaytonNolen** [comment]
Changed most of the objects we labeled Events to Gyms

**Comment by ClaytonNolen** [comment]
major issues, trying to revert back

**Comment by ClaytonNolen** [comment]
Fixed. moving forward.

**Comment by ClaytonNolen** [comment]
New type file made and type made called TEvent.

**Comment by ClaytonNolen** [comment]
Finishing up Eventlist bindings

**Comment by ClaytonNolen** [comment]
Helper function for the date was created.

**Comment by ClaytonNolen** [comment]
Committed and pushed changes. Will be looking into what is needed for the join page and if we should do it.

**Comment by ClaytonNolen** [comment]
After speaking with Jed and the others, that page is already coded just not pushed.

**Comment by ClaytonNolen** [comment]
Will need a function to register members to a gym. Will look into this now.

**Comment by ClaytonNolen** [comment]
Taking a break for dinner and family

**Comment by ClaytonNolen** [comment]
After looking back to start coding again I can not begin until my teammates push their branches. Will spend some time looking into the next steps beyond that.

**Comment by jedace** [comment]
Starting on pushing code and working on how to add ability for people to subscribe to gyms

**Comment by jedace** [comment]
Merges complete, looking at ways to customize application

**Comment by jedace** [comment]
Made changes to application that better suits scope of gym. Right now includes small changes of titles but want to work on changing creation of workouts

**Comment by jedace** [comment]
Finding ways to implement this with our proposed ideas in slack

**Comment by jedace** [comment]
Still working on side bar / quick menu

**Comment by jedace** [comment]
Side menu idea isn't working, may have to pivot to something else

**Comment by jedace** [comment]
Scrapping the work that was done as it broke the whole page. moving on to work on to looking at how users may be able to store their own gyms and workouts

**Comment by jedace** [comment]
Working more on storing workouts

**Comment by jedace** [comment]
Still working on ways to store workout

**Comment by jedace** [comment]
Can't get workout to save on page when one is created, stopping work for now

**Comment by ClaytonNolen** [comment]
Looking at merge code and checking if it works.

**Comment by ClaytonNolen** [comment]
Spoke to Daniel about scalability of the home page. Am looking at what else needs to be done for the auth side.

**Comment by ClaytonNolen** [comment]
Will need to finish the authentication side tomorrow and then plan out the next steps from there.

**Comment by ClaytonNolen** [comment]
Starting back up on finishing Auth. Specifically - Reg Member

**Comment by ClaytonNolen** [comment]
![Image 3-17-24 at 3 18 PM](https://github.com/ClaytonNolen/GymProgram/assets/91333063/97d0c38b-43e9-46f0-a02d-bb9a668c73fd)

Having an issue connecting to the backend and viewing the Object that holds the values. Should look like: 
![Screenshot 2024-03-17 at 3 19 05 PM](https://github.com/ClaytonNolen/GymProgram/assets/91333063/6f4d1cb1-5344-4992-839a-92d0c9f32251)

FROM: https://www.youtube.com/watch?v=3Q4fK1NdNMQ&t=3184s

**Comment by ClaytonNolen** [comment]
Working back on the Auth files. I will be ignoring the previous issue now.

**Comment by ClaytonNolen** [comment]
Adding to the EventInfo file, cont Auth.

**Comment by ClaytonNolen** [comment]
Having issues with types being called that do not exist.

![Screenshot 2024-03-17 at 9 00 17 PM](https://github.com/ClaytonNolen/GymProgram/assets/91333063/6c89c12e-1e07-486b-9d49-cbb53a33356d)

**Comment by ClaytonNolen** [comment]
Cannot figure out what the issue is. Will continue to look

**Comment by ClaytonNolen** [comment]
Am unsure what is wrong and will need to talk to the other teammates. Tomorrow I will continue coding and finish the code even with the error.

**Comment by Daniel-Haley** [comment]
Created another Firebase account to test connection. Still getting same errors

**Comment by ClaytonNolen** [comment]
Continuing work on the debugging issue. I believe we have narrowed it down to the CreateEvent file

**Comment by ClaytonNolen** [comment]
<img width="867" alt="Screenshot 2024-03-18 at 11 35 16 AM" src="https://github.com/ClaytonNolen/GymProgram/assets/91333063/a24164ea-61fa-4a22-8807-47698e63c66b">

Was able to fix issues in the CreatEvent File, which populated Jed's test but is not able to populate my own. Asking Jed to test his end while I work on fixing another issue in our EventList file. Hint: Snapshot issue.

[2024-03-18T16:17:11.225Z]  @firebase/firestore: Firestore (10.8.0): Uncaught Error in snapshot listener: FirebaseError: [code=permission-denied]: Missing or insufficient permissions.

**Comment by ClaytonNolen** [comment]
On second thought it very much could be the binding on the event page. Looking into that for a little longer.

**Comment by jedace** [comment]
Looking at issue found in class with read and writes not working, looking specifically at firestore securities

**Comment by jedace** [comment]
Continunig to look at potential rules to use, will need to pause after this

**Comment by jedace** [comment]
Working today with a focus on finalizing rules that will allow testing to work

**Comment by ClaytonNolen** [comment]
Caught up with Jed on fixing the issue. Code looks to work now but does have some security risk. While Jed reads more into that I will be looking into the creative side and discussing with Daniel + Kiefer on what entities we should add to the database.
