### ISSUE TITLE
Database Connection

### ISSUE THREAD

**Issue by Daniel-Haley** [ClaytonNolen/GymProgram#18]
Running into an error with getting connected to Firebase when trying to view the webpage in vite. It appears to be something to due with the API key.

**Comment by Daniel-Haley** [comment]
The API appears to be available but imports are not taken in the create page.svelte file. It is working on Clayton's machine and will debug sometime tomorrow. Most likely to due with a file path issue.

**Comment by crowleyk1** [comment]
Ran into same issue. Receiving "invalid api key". I found a video that might help: https://www.youtube.com/watch?v=pxH6YqNMLPg

**Comment by Daniel-Haley** [comment]
Needed .env file that includes pertinent information for Firebase connection to the project. Will need to include in the user manual because it appears that GitHub ignores the .env file for security reasons.
