### ISSUE TITLE
Gym Equipment Specifications

### ISSUE THREAD

**Issue by Daniel-Haley** [ClaytonNolen/GymProgram#22]
Determining which gym equipment and what data to collect from the machines.

**Comment by Daniel-Haley** [comment]
Took pictures of all of the equipment at the Robertson Center Gym.

**Comment by Daniel-Haley** [comment]
Starting to document equipment and will focus on machines before looking at free weight equipment.

**Comment by Daniel-Haley** [comment]
Uploading gym equipment pictures to my computer. Created a folder in the Google Drive called "Rob Pictures" that will store these pictures and any other of the Rob that we will be using

**Comment by Daniel-Haley** [comment]
Imported all of the equipment pictures into the "Rob Pictures" folder but they saved as HEIC images. After some research, PNG seems to be the best image type for image support and quality.

**Comment by Daniel-Haley** [comment]
Resuming work. Will be working on naming images and converting them to a PNG format so they are stored in the Drive that way.

**Comment by Daniel-Haley** [comment]
Looked up how to convert HEIC images into PNG format and renamed every image into its proper name.

**Comment by Daniel-Haley** [comment]
Researched best ways to track a workout and concluded that for now, focus on only weight, sets, and reps for what to track on each machine. Starting to document specific machine information in "Equipment Information/Tracking" doc within the "Project" folder in the Drive.

**Comment by Daniel-Haley** [comment]
Equipment is filled in and complete for possible options that we will be using. Will need to talk with the team about specifically what we want to include but it seems most realistic to start off with machines only and figure out the best way to implement free weight machines and those that can support multiple exercises.

**Comment by ClaytonNolen** [comment]
Brainstorming with Daniel on db entities and attributes

**Comment by ClaytonNolen** [comment]
IMG_0346.jpeg

**Comment by ClaytonNolen** [comment]
![Uploading Screenshot 2024-03-20 at 10.25.04 AM.png…]()

**Comment by Daniel-Haley** [comment]
![IMG_2273](https://github.com/ClaytonNolen/GymProgram/assets/111393255/7642ae1f-9977-4f4a-bace-4d393def9720)

Includes more information on how gym equipment details will be displayed.
