### ISSUE TITLE
Create gym & gym lists modifications

### ISSUE THREAD

**Issue by jedace** [ClaytonNolen/GymProgram#30]
Changing variables to better align with project goals as specified in meeting

**Comment by jedace** [comment]
Pushed changes on branch, need to update changes on gym page now to properly display new info

**Comment by Daniel-Haley** [comment]
Group going to be collectively working on developing a create gym page that will be able to see firebase data and test if everything works with the connection.

**Comment by jedace** [comment]
Create page properly works with firebase and showing values. Gym card displays this info too, now need to get the gym card binding correct to fix 500 error

**Comment by jedace** [comment]
Made more updates to events and types, still getting error when clicking on the gym cards

**Comment by jedace** [comment]
URL now updates correctly but still getting 500 error

**Comment by jedace** [comment]
Working on 500 error again. If no solution is found soon going to move on

**Comment by jedace** [comment]
Still looking at error, looking at database side of things

**Comment by jedace** [comment]
Can't find a fix, moving on to cleaning up display of gyms

**Comment by jedace** [comment]
Resuming work on gym displays

**Comment by jedace** [comment]
Double checking all types and variables are updated, not getting proper display of gym created

**Comment by jedace** [comment]
Looking at potential ways to add gym equipment

**Comment by jedace** [comment]
Still working on ways to add

**Comment by jedace** [comment]
Proving difficult to test ways to display with 500 error blocking the next page, will need to convene with group members to see if they know potential fixes
