### ISSUE TITLE
SU Equipment Info Page

### ISSUE THREAD

**Issue by Daniel-Haley** [ClaytonNolen/GymProgram#32]
Kiefer and I working on a page that displays equipment info for the Rob gym with pictures and descriptions. Should not interfere with database work that is going on

**Comment by Daniel-Haley** [comment]
Created a branch called "SU-Equipment Info" and have a plan to include equipment names, descriptions, muscle groups, and a picture of each equipment.

**Comment by crowleyk1** [comment]
Beginning work on page.

**Comment by crowleyk1** [comment]
Importing images from assets to SUInfo Page.

**Comment by crowleyk1** [comment]
Messing with the formatting of the page.

**Comment by crowleyk1** [comment]
Got the formatting in a decent place. Added a few rows of workout equipment. Taking a break for now.

**Comment by crowleyk1** [comment]
Continuing work on SUInfo Page.

**Comment by crowleyk1** [comment]
Almost done adding exercise machines to page.

**Comment by crowleyk1** [comment]
Finished adding exercise machines to the page.

**Comment by crowleyk1** [comment]
Started adding muscle groups to the machines.

**Comment by crowleyk1** [comment]
Continuing work on page.

**Comment by crowleyk1** [comment]
Added most of the muscle groups to the machines, but encountered a problem: some machines are specific to a single workout while others have many different workouts that can be done. Machines may need to be broken down into sub-categories with each possible exercise.

**Comment by crowleyk1** [comment]
Started adding descriptions to the exercises.

**Comment by crowleyk1** [comment]
Added more descriptions. We may need outside sources to get more accurate and elegant descriptions.

**Comment by crowleyk1** [comment]
Added more descriptions. I'll be handing the info page off to Daniel now.

**Comment by crowleyk1** [comment]
Added sources where I got some of the exercise descriptions

**Comment by Daniel-Haley** [comment]
Picking up where Kiefer left off on the equipment page. Adding descriptions and potentially going to work on image sizing.

**Comment by Daniel-Haley** [comment]
Deleted machines that we will not be using and adding more machine descriptions

**Comment by Daniel-Haley** [comment]
Finding sources to go along with descriptions and adding more

**Comment by Daniel-Haley** [comment]
Not all descriptions are completed but will start looking at how to make pictures appear larger

**Comment by Daniel-Haley** [comment]
Fixed images to where they fit the entire screen on the right column of the page. May work out spacing later but the images are much more visible now.

**Comment by Daniel-Haley** [comment]
Planning on adding a description of the project changes we discussed during Monday's class and finishing descriptions on the equipment info page.

**Comment by Daniel-Haley** [comment]
Included all of the ideas that were discussed in class on 3/25 about changes to the project. These details are in the "Current Work" doc in the Drive.

**Comment by Daniel-Haley** [comment]
Finishing last few descriptions with the machines and focusing more on tips about how more beginner users can use the equipment safely.
