### ISSUE TITLE
Creating Workouts

### ISSUE THREAD

**Issue by jedace** [ClaytonNolen/GymProgram#39]
Working with Clayton on feature that allows users to create a workout and stores this workout under the user. This will include a drop down of available equipment and a notes section for adding workout information that cannot be as easily tracked

**Comment by ClaytonNolen** [comment]
Getting up to speed and working with Jed on this.

**Comment by jedace** [comment]
Fixing issue where create button doesn't work

**Comment by ClaytonNolen** [comment]
Our create button is doing nothing and we are both searching for what broke it.

**Comment by jedace** [comment]
Fond older working version, manually going through to update variables

**Comment by ClaytonNolen** [comment]
We have successfully updated to an older version that works. Out next step will be to "trim the fat" of our unused variables.

**Comment by jedace** [comment]
Starting to look at workouts again. Looking at variables and where they are stored in database to ensure connections don't get broken again

**Comment by jedace** [comment]
Leaving them together as can't find what the issue database has with missing variables

**Comment by jedace** [comment]
Seeing if a drop down can get made for the workouts
