### ISSUE TITLE
Implementing Chart

### ISSUE THREAD

**Issue by Daniel-Haley** [ClaytonNolen/GymProgram#41]
Adding chart to repository and making the connection to Firebase.

**Comment by ClaytonNolen** [comment]
Starting by discussing what we need and which resources to pull from to begin this feature.

**Comment by Daniel-Haley** [comment]
Linked "Adding-Chart" to this Issue and updated the branch to currently be updated with the main branch.

**Comment by ClaytonNolen** [comment]
Ditto^^ @Daniel-Haley

**Comment by ClaytonNolen** [comment]
A new entity is need that will have the user ID with an attribute for our first benchmark we are measuring. 

UID -----> benchPress [135, 150, 165, 180]

**Comment by ClaytonNolen** [comment]
Have successfully been able to find and pull the User ID so that we can construct a entity from it later! LETS GO.
<img width="1526" alt="Screenshot 2024-04-01 at 7 15 08 PM" src="https://github.com/ClaytonNolen/GymProgram/assets/91333063/8b559f8f-d534-4529-843a-ae4d859ac1d3">

**Comment by Daniel-Haley** [comment]
Currently, I believe the main issue is that we do not have the library stored properly on our repository. Later, I am going through the step-by-step guide on Chart.js to see if I skipped any steps in the implementation.

**Comment by ClaytonNolen** [comment]
Starting back up. Goal is to create a button that populates the first index of an array, or something that can become that into our data base.

**Comment by Daniel-Haley** [comment]
Using https://www.chartjs.org/docs/latest/getting-started/usage.html to go through how to get an example chart

**Comment by ClaytonNolen** [comment]
<img width="1427" alt="Screenshot 2024-04-02 at 7 00 58 PM" src="https://github.com/ClaytonNolen/GymProgram/assets/91333063/7b8f4c5b-0c80-4ee1-a0a6-faa8793946cb">

This is the new test page that I am using to show the number we will input. I now will create a way to show the data that is inputed.

**Comment by Daniel-Haley** [comment]
Installed the chart.js and svelte wrapper class from here: https://www.npmjs.com/package/svelte-chartjs
Code is still getting an error that it can't find the module when importing a Line chart

**Comment by Daniel-Haley** [comment]
Figuring out why the file path won't connect on the Chart.svelte file. Taking a break but found this page that I will look over to try to debug why the chart.js module can't be found: https://stackoverflow.com/questions/36577943/cannot-find-module-chart-js

**Comment by Daniel-Haley** [comment]
Initial error fixed from adjusting how data how chart.js is imported. Found error from this link from the Chart.js website: https://github.com/SauravKanchan/svelte-chartjs
Now getting an error with the javascript data that is from the svelte example. Once this is fixed we should be able to view the chart.

**Comment by Daniel-Haley** [comment]
Data configuration still not working. It is a possibility that the svelte code I was looking at was using another plug-in. Going back through this video to try to find where I've been going wrong after looking at other sources.

**Comment by Daniel-Haley** [comment]
Switched back to https://www.youtube.com/watch?v=JvYK-X2Tf8E because it is using a more up-to-date version of chart.js. Ensuring that setup is accurate.

**Comment by ClaytonNolen** [comment]
Working on merging branches and testing if the vars upload

**Comment by ClaytonNolen** [comment]
The charts work and are connected to firebase.
