### ISSUE TITLE
Exercise/Workout Dropdown

### ISSUE THREAD

**Issue by jedace** [ClaytonNolen/GymProgram#44]
Our current textbox exercise needs to be transformed into a dropdown with preset exercises of the available machines

**Comment by jedace** [comment]
Still working on implementing dropdown menu

**Comment by jedace** [comment]
Dropdown button is populated, working on changing functionality and appearance to match website

**Comment by jedace** [comment]
Dropdown is still blinding and is not properly binded to database. stopping now

**Comment by jedace** [comment]
Resuming work on binding dropdown variables

**Comment by jedace** [comment]
Still wroking on issue with dropwdown variables not binding

**Comment by jedace** [comment]
Working with Clayton on similar issue of undefined variables

**Comment by jedace** [comment]
Back to working on binding exercises to variables in the database

**Comment by jedace** [comment]
Resuming work on typeerror

**Comment by jedace** [comment]
Fixed typeError. now working on display of create workout page

**Comment by jedace** [comment]
Still working on adding sets reps and weights to exercises

**Comment by jedace** [comment]
exercises now have sets reps and weights. working on making it so they all appear as one obx together, and ability to add multiple exercises to a workout

**Comment by jedace** [comment]
Still working on adding multiple exercises to a workout

**Comment by jedace** [comment]
Pausing

**Comment by jedace** [comment]
Resuming

**Comment by jedace** [comment]
Solving issue where adding additional exercises wipes previous exercises

**Comment by jedace** [comment]
Still having issues with adding multiple exercises to a workout

**Comment by jedace** [comment]
Working on same issue of not being able to add multiple exercises

**Comment by jedace** [comment]
Trying one final fix then stopping

**Comment by jedace** [comment]
Working again on errors stopping there from being multiple exercises on a workout

**Comment by crowleyk1** [comment]
Taking over work on create page

**Comment by crowleyk1** [comment]
Going to work on workouts page to display a users workouts

**Comment by crowleyk1** [comment]
Changed EventCard to display workouts horizontally rather than as a grid

**Comment by jedace** [comment]
Button no longer erases but still does not add multiple exercises

**Comment by crowleyk1** [comment]
Changed how workouts display on profile page. Also turned workouts into a button. The plan is to display the exercises of that workout when clicked.

**Comment by jedace** [comment]
Still not able to add multiple exercises

**Comment by jedace** [comment]
Tried adding dynamic html code, still doesnt work

**Comment by crowleyk1** [comment]
Looking at function to add multiple exercises

**Comment by crowleyk1** [comment]
Created sub branch to try some things out

**Comment by crowleyk1** [comment]
Still working to no avail

**Comment by crowleyk1** [comment]
Using some old code that I wrote for the workout page

**Comment by crowleyk1** [comment]
Trying to merge pieces of my code with Jed's

**Comment by crowleyk1** [comment]
Looking at adding multiple exercises to a workout again
