### ISSUE TITLE
Adding Chart pt2

### ISSUE THREAD

**Issue by ClaytonNolen** [ClaytonNolen/GymProgram#46]
Jed/Daniel/Claytons code is merged. The button is not working but we believe it because vars are currently expected!

**Comment by Daniel-Haley** [comment]
Still figuring out an error where a new chart can't be created. Now I am thinking most of the issues are because of chart.js version discrepency.

**Comment by Daniel-Haley** [comment]
Picking back up on https://www.youtube.com/watch?v=JvYK-X2Tf8E and its implementation. Going to finish to see if the error I have now will go away.

**Comment by Daniel-Haley** [comment]
Continuing to implement changes from the video and testing if they work.

**Comment by ClaytonNolen** [comment]
Back on. Working with Jed on why my button is not working.

**Comment by Daniel-Haley** [comment]
Finished chart and working on getting it to show up on one of our pages.  Setting up chart as a component and creating tag that will place it in a file.

**Comment by ClaytonNolen** [comment]
We have located the issue is with our UID information not being defined.

**Comment by ClaytonNolen** [comment]
Found a new method to input values in a Firebase - trying that out.

**Comment by ClaytonNolen** [comment]
https://www.youtube.com/watch?v=uVz47tr7vv0

**Comment by Daniel-Haley** [comment]
Chart finally shows up but needs editing to show up correctly and then need to figure out how it links to Firebase. WOO HOO!!

**Comment by ClaytonNolen** [comment]
Reading over some of the code we wrote yesterday and trying to understand what is going wrong. I only have about 30 minutes for this time period but later today will work on it more.

**Comment by Daniel-Haley** [comment]
Working on making the chart more presentable by fixing the size and spacing on the page. Will also be working on how to make the connection with Firebase.

**Comment by ClaytonNolen** [comment]
Code now works and is uploading to the database. I will be changing it to hold an array value in the field.

**Comment by Daniel-Haley** [comment]
Figuring out why there are duplicate graphs whenever I am trying to display it

**Comment by ClaytonNolen** [comment]
I have worked on changes but the field/data is always over writing it to just a string. Including the current data.

**Comment by Daniel-Haley** [comment]
Figured out how to only have one graph and center it. However, now I am not able to make the graph larger. I am going to commit the code and transition to figuring out how to link Firebase data.

**Comment by ClaytonNolen** [comment]
ITS WORKING!!! HAAHHAHA

**Comment by ClaytonNolen** [comment]
Daniel and I will be working together now to combine our code together. We have just now merged our branches.

**Comment by Daniel-Haley** [comment]
Watching this video on how to connect data but not sure if it will transition to Svelte: https://www.youtube.com/watch?v=AoIWp-yyQu4

**Comment by ClaytonNolen** [comment]
Done for the day. Daniel and I have made a game plan to import the data from our database tomorrow and use them in our charts.

**Comment by Daniel-Haley** [comment]
Video does not transition super well for Svelte but later going to implement plan to import data and then pull that to our chart.

**Comment by ClaytonNolen** [comment]
The charts are added and do work.
