### ISSUE TITLE
Research & Creative Works

### ISSUE THREAD

**Issue by crowleyk1** [ClaytonNolen/GymProgram#47]
Starting group work on the poster

**Comment by Daniel-Haley** [comment]
Going to put all poster work in "Poster Creation" and use this issue for other ideas in terms of presentation here

**Comment by Daniel-Haley** [comment]
Created and working on a doc called "Presentation Notes"  (in "Research and Creative Works") that will serve as a resource for tools and other notes for our presentations at RCWS and for the CS department next week.

**Comment by Daniel-Haley** [comment]
Added information to "Presentation Notes". Still in progress but have to stop working now and pick up later.

**Comment by Daniel-Haley** [comment]
Completed Research and Creative Works Presentation. Found rhythm of how we will present  on the 25th but will need to expand and hoping for a demo to demonstrate.
