### ISSUE TITLE
Poster Creating

### ISSUE THREAD

**Issue by ClaytonNolen** [ClaytonNolen/GymProgram#50]
This is a GitHub issue about to creating the poster for our Capstone Presentation.

**Comment by ClaytonNolen** [comment]
Starting the post now by modeling a previous students in our google drive.

**Comment by ClaytonNolen** [comment]
Change of plans, Daniel would like to colab instead of split up on fetching the code.

**Comment by jedace** [comment]
Looking at poster plans

**Comment by crowleyk1** [comment]
Beginning work on poster for today.

**Comment by jedace** [comment]
Working on poster

**Comment by Daniel-Haley** [comment]
Going to look at templates later once we have information down because that is our priority at the moment. Creating an updated version of the abstract that we can put in the poster.

**Comment by crowleyk1** [comment]
Added some logos of the tools we used for this project along with a short paragraph explaining them. Also added some bullet points for the challenges section.

**Comment by jedace** [comment]
Still working on poster

**Comment by Daniel-Haley** [comment]
Completed updated abstract and added it to the poster. Helping Clayton with issues he was running into on his branch.

**Comment by Daniel-Haley** [comment]
Looked at more templates but we reorganized the size of the previous page. Reviewing current progress and will pick up later.

**Comment by jedace** [comment]
Stopping work on poster

**Comment by Daniel-Haley** [comment]
Fixing Colors and Sizing on our poster so it can be reviewed

**Comment by Daniel-Haley** [comment]
Colors obtained from https://www.southwestern.edu/marketing-and-communications/style-guide/color-palette/
Increased text size and moved around information to fit poster.

**Comment by jedace** [comment]
Making modifications to poster

**Comment by jedace** [comment]
Stopping

**Comment by Daniel-Haley** [comment]
Reviewing changes that need to be made to the poster and figuring out final pictures that need to be included on the poster.

**Comment by Daniel-Haley** [comment]
Going though and taking away comments that have been attended to. Creating space for other pictures and will update data analysis description.

**Comment by Daniel-Haley** [comment]
Updated and added a picture of the main page to the poster. Need to add descriptions for data analysis and SUInfo page before all of the text is there.

**Comment by Daniel-Haley** [comment]
Added descriptions on the poster about the SU equipment info page and data visuals with chart.js. Working on making the home page look better including the nav bar.

**Comment by Daniel-Haley** [comment]
Poster completed and printed on 4/12. Jed has the poster for us to present Tuesday at the Research and Creative Works Symposium.

**Comment by Daniel-Haley** [comment]
Poster Complete
