### ISSUE TITLE
Fetch Data

### ISSUE THREAD

**Issue by ClaytonNolen** [ClaytonNolen/GymProgram#51]
The ability, hopefully a helper file/method, that we can use to fetch data from our data base.

**Comment by Daniel-Haley** [comment]
Researching how to pull data from Firebase and potentially put it into an array.

**Comment by ClaytonNolen** [comment]
Currently working on a fetch method in our Firebase.ts file that were going to call and test in our chart file.

**Comment by Daniel-Haley** [comment]
Working with Clayton on the fetch method

**Comment by ClaytonNolen** [comment]
The fetchData method has no errors and I will be testing what we are getting in the web app.

**Comment by Daniel-Haley** [comment]
Transitioned to working on the poster. Found a potential template and will determine what sections to work on. Located in "Research and Creative Works" in the Drive

**Comment by ClaytonNolen** [comment]
Our fetch data function is not showing us receiving any information as found in our dev tools/console.

**Comment by ClaytonNolen** [comment]
have not been able to fix this issue and understand. Might work on it later.

**Comment by ClaytonNolen** [comment]
Working with capstone group and now I have an error with our firebase file.

**Comment by ClaytonNolen** [comment]
Reviewing code and online resources to fetch data from the Firebase. Previous attempts have not been working.

**Comment by ClaytonNolen** [comment]
I have addressed multiple issues in the code. Although this code be done in a much more scalable approach - it works!

What I have done is fetch the data from Firebase strictly from the current user. This data is then displayed on the chart because the data is stored onto an array. What is left is to clean up and touch up how exactly we would like the data to be displayed and how much of it we want.

**Comment by ClaytonNolen** [comment]
Fetch data can be found in the Chart file.
