### ISSUE TITLE
Upgrading Charts

### ISSUE THREAD

**Issue by ClaytonNolen** [ClaytonNolen/GymProgram#53]
Making the charts look more appropriate for UI and the specific data they are collecting.

**Comment by ClaytonNolen** [comment]
I was not the first to develop and use these charts so I would like to take the time to learn more about them. I have done a lot of work binding them to Firebase and fetching the data. However this work is much more design and UI.

**Comment by ClaytonNolen** [comment]
These have been my favorite resources so far:
 https://www.youtube.com/watch?v=ZpfseYy5Hxg
 https://www.chartjs.org/

**Comment by ClaytonNolen** [comment]
<img width="1654" alt="Screenshot 2024-04-11 at 8 44 42 PM" src="https://github.com/ClaytonNolen/GymProgram/assets/91333063/fdd60036-975c-4236-9da5-f5fdf46a0652">

Am having issues using this data.

**Comment by ClaytonNolen** [comment]
Taking a break!

**Comment by Daniel-Haley** [comment]
Working on how to improve the view of the charts and where they are located in the app.

**Comment by Daniel-Haley** [comment]
Going through this video to find styling tips for charts: https://www.youtube.com/watch?v=NySBh_DIRlg. Will try to add chart border title and will create a branch for this and other styling changes

**Comment by Daniel-Haley** [comment]
Chart is now not working but I believe it is because my own account on the app needs more data.

**Comment by Daniel-Haley** [comment]
Comment that should have been 30 min ago but didn't send: Added test page back to the navbar so that test data can be entered. Talked to Clayton and confirmed that all of the existing data had been wiped from Firebase.
Now: Added Chart title for bench Press. Now need to figure out how to change other chart aspects. Taking a break for now.

**Comment by Daniel-Haley** [comment]
Continuing work on making graphs look better

**Comment by Daniel-Haley** [comment]
Going through same video as earlier and learned more about where to make changes in the chart and how to add lines if we wanted to make a large graph. Made the current chart dynamic and fixing labels/colors

**Comment by Daniel-Haley** [comment]
Changed line color to Southwestern gold and messed around with other components of chart. Looking at different components on the chart.js website. Getting off now but there is a bug whenever the vite server is opened, the chart doesn't show until data is input.
