### ISSUE TITLE
Multiple Exercises 

### ISSUE THREAD

**Issue by crowleyk1** [ClaytonNolen/GymProgram#54]
Starting new branch to test some ideas

**Comment by crowleyk1** [comment]
Still working on create page

**Comment by crowleyk1** [comment]
found a resource that might be useful: https://svelte.dev/repl/a750718bed5a4a0eac9085b90b1adc3e?version=4.2.0

**Comment by crowleyk1** [comment]
Couldn't get package from previous link to work

**Comment by crowleyk1** [comment]
created 2d array for exercise but all values are overwritten when new values are added. Stopping work for now.

**Comment by crowleyk1** [comment]
Starting work on create page again

**Comment by crowleyk1** [comment]
Got exercises to appear on screen after adding them

**Comment by crowleyk1** [comment]
running out of ideas. Can't find a sources online that work

**Comment by crowleyk1** [comment]
I think i've narrowed down the problem to a single line

**Comment by crowleyk1** [comment]
I don't know what else to do. Svelte is stupid

**Comment by crowleyk1** [comment]
Continuing work

**Comment by crowleyk1** [comment]
no progress

**Comment by crowleyk1** [comment]
fixed the issue. now multiple exercises can be created under a workout

**Comment by crowleyk1** [comment]
copying some of Jed's code over

**Comment by crowleyk1** [comment]
Working on adding placeholder for dropdown box

**Comment by crowleyk1** [comment]
Taking a break for now

**Comment by jedace** [comment]
Looking at work and seeing if database issue can be fixed

**Comment by jedace** [comment]
Changing methods around

**Comment by jedace** [comment]
Attempting to fix doc errors

**Comment by jedace** [comment]
Still fixing doc issues

**Comment by jedace** [comment]
Doc issue gone but still not saving to db

**Comment by jedace** [comment]
Stopping now, will need to look back at previous solutions for similar issues

**Comment by crowleyk1** [comment]
Testing out idea to eliminate the need for a nested array

**Comment by crowleyk1** [comment]
Code works locally but doesn't appear on DB

**Comment by jedace** [comment]
Testing code from Kiefer on DB

**Comment by crowleyk1** [comment]
Updating eventcard and TEvents to reflect changes on create page

**Comment by crowleyk1** [comment]
Added a date field to create page.

**Comment by jedace** [comment]
Updating code

**Comment by crowleyk1** [comment]
Beginning work with Jed and Daniel

**Comment by jedace** [comment]
Working on storing the workouts created by a user under their userID

**Comment by crowleyk1** [comment]
userID is now stored in workouts but pattern matching on workouts page is not working

**Comment by jedace** [comment]
Fixing issue where no workouts are displayed

**Comment by crowleyk1** [comment]
Pattern matching may be working now. Need further testing.

**Comment by crowleyk1** [comment]
merged with main. Only workouts created by the user appear to that user.
