### ISSUE TITLE
Color Theme / Styling

### ISSUE THREAD

**Issue by Daniel-Haley** [ClaytonNolen/GymProgram#57]
Planning on changing the color scheme of the website and other styling changes. Possibilities that we can change our hover effects, buttons, and transitions into new pages.

**Comment by Daniel-Haley** [comment]
Updated colors of the page to fit gray, black, and gold school colors. Made these changes in the tailwind.config file that allows us to use custom colors throughout the app.

**Comment by crowleyk1** [comment]
Trying out some different color schemes

**Comment by crowleyk1** [comment]
Added some yellow to info page and create page. Also made some tweaks to margins and fixed some text that was the same color as the background on the create page. Done for tonight.

**Comment by crowleyk1** [comment]
Continuing work on color scheme

**Comment by Daniel-Haley** [comment]
Continuing to work on styling and clean up code

**Comment by Daniel-Haley** [comment]
Continuing to change colors
